include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - require_trailing_commas

analyzer:
  exclude:
    - "build/**"
    - "script/**"
    - "**/*.g.dart"
  errors:
    invalid_annotation_target: ignore
