name: energy_drink
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.7.0
  dio: ^4.0.6
  provider: ^6.0.4
  flutter_layout_grid: ^2.0.1
  shared_preferences: ^2.0.15
  connectivity_plus: ^2.3.9
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  #flutter pub run build_runner build
  build_runner: ^2.2.0
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  test: ^1.21.1

flutter:
  uses-material-design: true
  #generate: true
  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
