name: End-to-End 12 test mobile app
on: workflow_dispatch
jobs:
  end_to_end_test:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: ./mobile_app

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - uses: subosito/flutter-action@v2

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: AVD Cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29

      - name: Cache AVD Snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: pixel_xl
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: End-to-End Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: pixel_xl
          script: flutter test ./integration_test/script_12_test.dart
          working-directory: ./mobile_app
