name: Mobile app
on: push
jobs:
  test:
    name: Test mobile app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
      - working-directory: ./mobile_app
        run: flutter pub get
      - working-directory: ./mobile_app
        run: flutter test --coverage

  integration_test:
    name: Integration test mobile app
    runs-on: macos-latest

    defaults:
      run:
        working-directory: ./mobile_app

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - uses: subosito/flutter-action@v2

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: AVD Cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29

      - name: Cache AVD Snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: pixel_xl
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: pixel_xl
          script: flutter test integration_test
          working-directory: ./mobile_app

  # integration_test:
  #   name: Integration test mobile app
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: subosito/flutter-action@v1
  #     - uses: reactivecircus/android-emulator-runner@v2.27.0
  #       with:
  #         target: default
  #         api-level: 21
  #         arch: x86_64
  #         profile: Nexus 6
  #         working-directory: ./mobile_app
  #         script: |
  #           flutter doctor -v
  #           flutter devices
  #           flutter test ./integration_test/script_1_test.dart
